#!/usr/bin/env bash
# Bash script that will display information about subdomains.
domain_function () {
    command=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $command" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}
if [ "$#" == 1 ]
then
  domain_function "$1" "www"
  domain_function "$1" "lb-01"
  domain_function "$1" "web-01"
  domain_function "$1" "web-02"
elif [ "$#" == 2 ]
then
  domain_function "$1" "$2"
fi
