#!/usr/bin/env bash
#  Bash script containing commands to automatically
# configure a Ubuntu machine so that /redirect_me is redirecting to
# another page "301 Moved Permanently".

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod 666 /var/www/html/index.nginx-debian.html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
