#!/usr/bin/env bash
#  Bash script containing commands to automatically
# configure a Ubuntu machine have a custom 
# 404 page that contains the string Ceci n'est pas une page".

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod 666 /var/www/html/index.nginx-debian.html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo touch /var/www/html/404.html
sudo chmod 666 /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i '/listen 80 default_server/a error_page 404 /404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
