#!/usr/bin/env bash
#Bash script managing manage_my_process

case "$1" in
    "start")
	./manage_my_process
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
        ;;
    "stop")
	pid=$(cat /var/run/my_process.pid)
	kill $pid
	rm -f /var/run/my_process.pid
	echo "manage_my_process stopped"
        ;;
    "restart")
	kill "$(cat /var/run/my_process.pid)"
	rm -f /var/run/my_process.pid
        ./manage_my_process restart
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process restarted"
        ;;
    *)
	echo "Usage: manage_my_process {start|stop|restart}"
esac
